"""Initial migration

Revision ID: 03f04ab63de9
Revises: 57a4ba3b44f0
Create Date: 2024-10-07 17:17:54.786074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f04ab63de9'
down_revision: Union[str, None] = '57a4ba3b44f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('client_message', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('type_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'type_message')
    op.drop_column('orders', 'client_message')
    # ### end Alembic commands ###
