"""Initial migration

Revision ID: 57a4ba3b44f0
Revises: e9eab4636dae
Create Date: 2024-10-07 15:28:50.840773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a4ba3b44f0'
down_revision: Union[str, None] = 'e9eab4636dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('owner_email', sa.String(), nullable=True))
    op.drop_column('sites', 'ownert_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('ownert_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sites', 'owner_email')
    # ### end Alembic commands ###
