"""Initial migration

Revision ID: 64c9da794915
Revises: 899d4e21b98c
Create Date: 2024-10-07 14:50:12.205494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c9da794915'
down_revision: Union[str, None] = '899d4e21b98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('client_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'client_name')
    # ### end Alembic commands ###
