"""Fix migrations after product_sizes drop

Revision ID: 7920755b2195
Revises: bf681be069ec
Create Date: 2024-12-07 19:53:16.845589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7920755b2195'
down_revision: Union[str, None] = 'bf681be069ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_color_id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_color_id'], ['product_colors.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.add_column('colors', sa.Column('sizes', sa.JSON(), nullable=True))
    op.drop_column('order_items', 'product_syze_id')
    op.drop_column('orders', 'delivery_method')
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('delivery_method', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('product_syze_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('colors', 'sizes')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
