"""Initial migration

Revision ID: 899d4e21b98c
Revises: f2d268dac233
Create Date: 2024-10-06 00:33:50.210621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899d4e21b98c'
down_revision: Union[str, None] = 'f2d268dac233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'site_domain',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('sites_site_domain_key', 'sites', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sites_site_domain_key', 'sites', ['site_domain'])
    op.alter_column('sites', 'site_domain',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
