"""Initial migration

Revision ID: 94cd79c63a51
Revises: fdd2987777bb
Create Date: 2025-01-21 15:49:59.934054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94cd79c63a51'
down_revision: Union[str, None] = 'fdd2987777bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'title_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('categories', 'title_ru',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('products', sa.Column('video', sa.String(), nullable=True))
    op.drop_column('products', 'slides')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('slides', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'video')
    op.alter_column('categories', 'title_ru',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('categories', 'title_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
