"""Initial migration

Revision ID: 950f017052f7
Revises: 8e164ffb2086
Create Date: 2024-11-22 21:52:36.656989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950f017052f7'
down_revision: Union[str, None] = '8e164ffb2086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('products', sa.Column('slides', sa.String(), nullable=True))
    op.add_column('products', sa.Column('video', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'video')
    op.drop_column('products', 'slides')
    op.drop_column('products', 'avatar')
    # ### end Alembic commands ###
