"""Initial migration

Revision ID: e9eab4636dae
Revises: 37b5c85faade
Create Date: 2024-10-07 15:24:45.593878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9eab4636dae'
down_revision: Union[str, None] = '37b5c85faade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('ownert_email', sa.String(), nullable=True))
    op.drop_column('sites', 'True')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('True', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sites', 'ownert_email')
    # ### end Alembic commands ###
