"""Initial migration

Revision ID: f2d268dac233
Revises: 
Create Date: 2024-10-06 00:27:37.135212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d268dac233'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(), nullable=False),
    sa.Column('site_domain', sa.String(), nullable=False),
    sa.Column('site_owner', sa.Integer(), nullable=True),
    sa.Column('owner_telegram', sa.String(), nullable=True),
    sa.Column('site_description', sa.String(), nullable=True),
    sa.Column('site_category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_domain'),
    sa.UniqueConstraint('site_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(), nullable=False),
    sa.Column('order_status', sa.Enum('received', 'accepted', 'processed', 'confirmed', 'shipped', 'delivered', 'canceled', name='orderstatus'), nullable=False),
    sa.Column('telegram_notification', sa.Enum('waiting', 'delivered', name='telegramnotification'), nullable=False),
    sa.Column('client_phone', sa.String(), nullable=False),
    sa.Column('client_email', sa.String(), nullable=True),
    sa.Column('client_city', sa.String(), nullable=True),
    sa.Column('client_address', sa.String(), nullable=True),
    sa.Column('delivery_method', sa.Enum('courier', 'mail', 'self', name='deliverymethod'), nullable=True),
    sa.Column('payment_method', sa.Enum('cash', 'remittance', 'online', name='paymentmethod'), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('product_color', sa.String(), nullable=True),
    sa.Column('product_size', sa.String(), nullable=True),
    sa.Column('product_quantity', sa.Integer(), nullable=True),
    sa.Column('price_product', sa.Float(), nullable=True),
    sa.Column('price_taxes', sa.Float(), nullable=True),
    sa.Column('price_delivery', sa.Float(), nullable=True),
    sa.Column('price_total', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received', sa.TIMESTAMP(), nullable=False),
    sa.Column('client_ip', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['site_name'], ['sites.site_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['site_name'], ['sites.site_name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_updates_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('previous_state', sa.JSON(), nullable=False),
    sa.Column('current_state', sa.JSON(), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.Enum('posted', 'checked', name='orderupdatestatus'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_updates_logs')
    op.drop_table('sites_admins')
    op.drop_table('orders')
    op.drop_table('user')
    op.drop_table('sites')
    # ### end Alembic commands ###
