"""Fix migrations after product_sizes drop

Revision ID: fdd2987777bb
Revises: 55fdb08896f2
Create Date: 2024-12-07 20:04:57.994827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdd2987777bb'
down_revision: Union[str, None] = '55fdb08896f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('colors', 'sizes')
    op.add_column('product_colors', sa.Column('sizes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_colors', 'sizes')
    op.add_column('colors', sa.Column('sizes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
